from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from . import views

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name='basal/main.html'), 
        name='main'),
    url(r'^user_login/$', 'django.contrib.auth.views.login',
        {'template_name': 'basal/login.html'}, name='user_login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        name='logout'),
    url(r'^user_create/$', views.UserCreateView.as_view(), 
        name='user_create'),
    url(r'^user_update/$', views.UserUpdateView.as_view(), 
        name='user_update'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
#    url(r'^dashboard/my_rsvps/$', views.MyRSVPsView.as_view(), name='my_rsvps'),
#    url(r'^dashboard/my_events/$', views.MyEventsView.as_view(), 
#        name='my_events'),
#    url(r'^address_list/$', views.AddressListView.as_view(), 
#        name='address_list'),
    url(r'^address_detail/(?P<pk>\d+)/$', views.AddressDetailView.as_view(), 
        name='address_detail'),
    url(r'^user_tag_delete/(?P<pk>\d+)/$', views.user_tag_delete, 
        name='user_tag_delete'),
    url(r'^user_tag_create/$', views.user_tag_create, 
        name='user_tag_create'),
    url(r'^address_create/$', views.AddressCreateView.as_view(), 
        name='address_create'),
    url(r'^address_update/(?P<pk>\d+)/$', views.AddressUpdateView.as_view(), 
        name='address_update'),
    url(r'^address_delete/(?P<pk>\d+)/$', views.AddressDeleteView.as_view(), 
        name='address_delete'),
    url(r'^user_image_list/$', views.UserImageListView.as_view(), 
        name='user_image_list'),
    url(r'^user_image_detail/(?P<pk>\d+)/$', 
        views.UserImageDetailView.as_view(), name='user_image_detail'),
    url(r'^user_image_create/$', views.UserImageCreateView.as_view(), 
        name='user_image_create'),
    url(r'^user_image_update/(?P<pk>\d+)/$', 
        views.UserImageUpdateView.as_view(), name='user_image_update'),
    url(r'^user_image_delete/(?P<pk>\d+)/$', 
        views.UserImageDeleteView.as_view(), name='user_image_delete'),
    url(r'^user_image_create_api/$', views.UserImageCreateAPIView.as_view(), 
        name='user_image_create_api'),
)
